apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: robusta
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo
    spec:
      serviceAccountName: default
      securityContext:
        {}
      volumes:
      - name: minimounted
        hostPath:
          path: /Users/salama/data/mongo
      containers:
        - name: mongo
          image: "mongo"
          imagePullPolicy: IfNotPresent
          env:
          - name: MONGODB_INITDB_ROOT_USERNAME
            value: username
          - name: MONGODB_INITDB_ROOT_PASSWORD
            value: password
          volumeMounts:
            - name: minimounted
              mountPath: /data/db
          ports:
            - name: http
              containerPort: 27017
              protocol: TCP
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-persistent-volume
# spec:
#   storageClassName: local-storage
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   local:
#     path: /Users/salama/data/mongo
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: kubernetes.io/hostname
#               operator: In
#               values:
#                 - minikube
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: local-persistent-volume-claim
# spec:
#   storageClassName: local-storage
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 9Gi